### ISSUE TITLE
Ensure consistent globe radius (PlateCarree)

### ISSUE THREAD

**Issue by snowman2** [SciTools/cartopy#1644]
### Description

With PROJ 6+ using the new API we see this error with PlateCaree:
```
Error creating Transformer from CRS.: (Internal Proj Error: proj_create_operations: Source and target ellipsoid do not belong to the same celestial body)
```
More information about this issue:

- https://lists.osgeo.org/pipermail/proj/2019-March/008390.html
- https://lists.osgeo.org/pipermail/proj/2019-May/008586.html

Related: #709

This is a blocker for #1140 and #1477

### TODO:
Ref: https://github.com/SciTools/cartopy/pull/1252#issuecomment-508869567

 - [ ]  Make a new lat/lon projection that takes degrees
 - [ ]  Add an EquidistantCylindrical projection that works like everything else with regards to globes
 - [ ]  Deprecate PlateCarree, or at least its current behavior

**Comment by snowman2** [comment]
Closed by #1808
