### ISSUE TITLE
Cartopy v0.11.0 release

### ISSUE THREAD

**Issue by cpelley** [SciTools/cartopy#435]
- [x] Provide projection-aware tick formatters. https://github.com/SciTools/cartopy/pull/401 merged
- [X] ~~Consider reference documentation auto generation https://github.com/SciTools/cartopy/pull/431~~
- [x] **Major bug in EuroPP projection, https://github.com/SciTools/cartopy/issues/436**
- [x] **Broken gallery example https://github.com/SciTools/cartopy/issues/438.**
- [x] Add reference documentation for those which are referenced in what's new https://github.com/SciTools/cartopy/pull/440
- [x] Milestone tidy
  - [x] Documenting installation options (https://github.com/SciTools/cartopy/issues/430, https://github.com/SciTools/cartopy/pull/397)
  - [x] Determine remaining viable tickets and request migration to 0.12.0 milestone.
- [x] Investigate the two failing tests which result from image changes in moving to conda travis install https://github.com/SciTools/cartopy/pull/432
- [x] Documentation publish
- [x] Google post announcement
- [x] Create 0.11.x branch
- [x] Google post announcement
- [x] Tag 0.11.0 release
- [x] Google post announcement

Time permits:
- [ ] Remove/change tests which are reliant on the matplotlib backend
